#!/bin/bash
cd /opt/ManualLayout
git stash -a
git pull
chmod +x /opt/ManualLayout/compile
chmod +x /opt/ManualLayout/setup
chmod +x /opt/ManualLayout/update
if [ -e ~/.bashrc ]
  then
    cp ~/.bashrc /opt/ManualLayout/.bashrc
fi
cd ~/
echo "Update Complete"
